---
- name: 'Install locales'
  tags: 'locales'
  sudo: 'yes'
  apt: >
    pkg=locales
    state=latest
    update_cache=true

- name: 'Install language packs'
  tags: 'locales'
  sudo: 'yes'
  apt: >
    pkg={{ item }}
    state=latest
    update_cache=true
  with_items: 'locale_language_packs'
  register: 'locale_languages'

- name: 'Reconfigure dpkg'
  tags: 'locales'
  sudo: 'yes'
  command: 'dpkg-reconfigure locales'
  when: 'locale_languages.changed'

- name: 'Detect locale configuration file'
  tags: 'locales'
  stat: 'path=/var/lib/locales/supported.d/local'
  register: 'locale_configuration'

- name: 'Create locale configuration file'
  tags: 'locales'
  sudo: 'yes'
  file: >
    path=/var/lib/locales/supported.d/local
    state=touch
  when: 'not locale_configuration.stat.exists'

- name: 'Configure system locale'
  tags: 'locales'
  sudo: 'yes'
  locale_gen: >
    name={{ locale }}.{{ encoding }}
    state=present
  tags: 'locales'

- name: 'Export LC_ALL environment variable in ~/.profile'
  tags: 'locales'
  lineinfile: >
    dest=/home/{{ locales_user }}/.profile
    create=yes
    line="export LC_ALL={{ locale }}.{{ encoding }}"

- name: 'Group by Distribution'
  hosts: 'all'
  tasks:
    - group_by: 'key=${ansible_distribution}'

- name: 'Set Time Zone'
  tasks:
    - name: 'Set timezone variables'
      copy: >
        content='Etc/UTC'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
      notify:
        - 'update timezone'
  handlers:
    - name: 'update timezone'
      command: 'dpkg-reconfigure --frontend noninteractive tzdata'